export const storeProducts = [
  {
    name: "bonsai ficus retusa (8 ans)",
    category: "soleil",
    id: 8,
    price: 105,
    detail:
      "Ficus. Les arbres classés comme d'intérieur sont des arbres qui viennent pour la plupart des climats tropicaux et ne peut donc résister à des températures basses. Nous devons les placer à l'intérieur des maisons, toujours près d'une source de lumière naturelle. Plante tropicale à feuilles persistantes, appréciée pour sa résistance et l'émission de racines aériennes qui lui donnent son caractère.",
    subs: [
      "Feuillage vert toute l'année",
      "Racines aériennes",
      "Facile de culture",
    ],
    entretienEtPlantation: [
      "Arrosage: abondant en été et modéré en hiver",
      "Période de plantation: rempotage tous les 2 ans",
      "Niveau de soin: facile",
      "Exposition: soleil",
      "Composition du sol: normal",
      "Humidité du sol: normal",
      "Température minimale: 15°C",
      "Utilisation pour la maison: veranda,intérieur",
    ],
    caracteristiquesVegetales: [
      " Feuillage décoratif: Non",
      "Feuillage: persistant",
    ],
    botanique: [
      "Origine: Inde, Java, Chine",
      "Température minimale : 15°C",
      "Famille: Moracées",
    ],
    img: ["images/soleil3.jpg", "images/soleil31.jpg", "images/soleil32.jpg"],
    inCart: false,
    count: 0,
    total: 0,
  },

  {
    name: "ficus microcarpa ginseng",
    category: "soleil",
    id: 9,
    detail:
      "Ficus ou figuier. Les arbres classés comme arbres d’intérieur viennent pour la plupart de climats tropicaux et ne peuvent donc pas résister à des températures basses. Ils doivent être placés à l'intérieur de la maison, toujours près d'une source de lumière naturelle. Arbre tropical à feuillage persistant. Très apprécié pour sa grande résistance, et l’émission de racines aériennes, qui lui donnent beaucoup de caractère.",
    subs: [
      "Aspect bonsaï très décoratif avec sa forme travaillée en S",
      "Feuillage lustré vert foncé",
      "Se plait dans toutes les pièces de la maison",
      "Le bonsaï du débutant.",
    ],
    entretienEtPlantation: [
      "Arrosage: normal",
      "Niveau de soin : facile",
      "Exposition: soleil,mi-ombre",
      "Température minimale: 10°C",
      "Utilisation pour la maison: intérieur",
    ],
    caracteristiquesVegetales: [
      "Feuillage décoratif: Non",
      "Couleur feuille: vert",
      "Feuillage: persistant",
    ],
    botanique: [
      "Origine: Inde et Sri Lanka",
      "Espèce: microcarpa",
      "Température minimale: 10°C",
      "Nom botanique : Ficus microcarpa 'Ginseng', syn Ficus retusa",
      "Famille: Moracées",
    ],
    price: 120,
    img: ["images/soleil4.jpg", "images/soleil41.jpg", "images/soleil42.jpg"],
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    name: "Bonsai Zelkova (16 ans)",
    category: "soleil",
    id: 10,
    detail:
      "Zelkova parvifolia. Bonsaï 16 Ans. Orme. Les arbres classés comme d'intérieur sont des arbres qui viennent pour la plupart des climats tropicaux et ne peut donc résister à des températures basses. Nous devons les placer à l'intérieur des maisons, toujours près d'une source de lumière naturelle. Arbre à feuilles Semi-caduque. Très apprécié par la petite taille de ses feuilles et son écorce qui pèle.",
    subs: [
      "Un arbre particulièrement décoratif",
      "S'adapte à tous les styles déco",
      "Un magnifique feuillage graphique",
    ],
    entretienEtPlantation: [
      "Arrosage: abondant en été, modéré au printemps.",
      "Période de plantation: rempotage tous les 2 ans avant le bourgeonnement",
      "Exposition: soleil",
      "Humidité du sol : humide",
      "Température minimale: 15°C",
      "Utilisation pour la maison: veranda,intérieur",
    ],
    caracteristiquesVegetales: [
      "Feuillage décoratif: Non",
      "Couleur fleur: vert",
      "Feuillage: semi-persistant",
      "Période de floraison: printemps",
    ],
    botanique: [
      "Température minimale: 15°C",
      "Nom botanique: Zelkova ou Ulmus",
      "Famille: Ulmacées",
    ],
    price: 520,
    img: ["images/soleil5.jpg", "images/soleil51.jpg", "images/soleil52.jpg"],
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    name: "palmier phoenix canariensis",
    category: "soleil",
    id: 7,
    detail:
      "Le palmier des Canaries, emblématique de la côte d'Azur, orne promenades de bord de mer, parcs et places du Sud. Victime de parasites, il disparaît peu à peu du paysage méditerranéen, mais constitue toujours un sujet ornemental exceptionnel dans un jardin.",
    subs: [
      "Feuillage vert toute l'année",
      "Racines aériennes",
      "Facile de culture",
    ],
    entretienEtPlantation: [
      "Arrosage: Très modéré",
      "Niveau de soin: très facile",
      "Exposition: soleil",
      "Composition du sol: riche en humus",
      "Température minimale: 15°C",
      "Température maximale: 30°C",
    ],
    caracteristiquesVegetales: [
      "Feuillage décoratif : Non",
      "Couleur feuille: vert",
      "Saison d'intérêt: printemps,été,automne,hiver",
      "Feuillage: persistant",
    ],
    botanique: [
      "Espèce: canariensis",
      "Température minimale : 15°C",
      "Nom botanique: Phoenix canariensis",
      "Famille: Palmiers",
    ],
    price: 50,
    img: ["images/soleil2.jpg", "images/soleil21.jpg", "images/soleil22.jpg"],
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    name: "yucca 2 troncs",
    category: "soleil",
    id: 6,
    detail:
      "Le yucca est grand classique pour l’intérieur que l’on apprécie par sa facilité d’entretien et sa rusticité.Bien que de croissance lente, le yucca peut atteindre près de 1,5m de hauteur. Il sera idéal dans une pièce lumineuse voire ensoleillée, la véranda ou le séjour par exemple.En option avec cette plante, les cache-pots Brussels, disponibles en de nombreuses couleurs dans les produits associés. L’idéal pour éviter les soucoupes disgracieuses et donner une note déco à votre plante verte.Plante dépolluante : le yucca est efficace contre l’ammoniac, le benzène et le monoxyde de carbone.En cas de gelées, l’expédition des plantes d’intérieur pourra être suspendue afin d’éviter la réception de plantes endommagées par le froid.",
    subs: [
      "Facile d'entretien",
      "Idéal dans une pièce lumineuse voire ensoleillée",
      "Plante dépolluante",
    ],
    entretienEtPlantation: [
      "Arrosage: normal",
      "Niveau de soin: très facile",
      "Exposition: soleil",
      "Composition du sol: normal",
      "Température minimale: °C",
      "Utilisation pour la maison: terrasse,veranda,intérieur",
    ],
    caracteristiquesVegetales: [
      "Feuillage décoratif: Non",
      "Largeur à maturité :  1,2 m",
      "Hauteur à maturité: 1,5 m",
    ],
    botanique: [
      "Rusticité: non rustique",
      "Espèce: elephantipes",
      "Température minimale: °C",
      "Nom botanique: Yucca elephantipes",
      "Famille: Agavacées",
    ],
    price: 30,
    img: ["images/soleil1.jpg", "images/soleil12.jpg", "images/soleil11.jpg"],
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    name: "palmier nain chamaedorea elegans",
    category: "mi-ombre",
    id: 4,
    detail:
      "Les Chamaedorea sont des petits palmiers d'intérieur de la famille des Arécacées, originaires d'Amérique du sud, d'Amérique centrale et du Mexique, où ils poussent dans des forêts humides, parfois montagneuses, souvent à l'ombre d'arbres plus grands. Ces plantes apprécient volontiers les situations ombragées, sauf pour certaines espèces plus grandes qui acceptent le soleil.",
    subs: [
      "Décoratif",
      "Feuilles étroites bordées de rouge",
      "Idéal dans de petits espaces",
    ],
    entretienEtPlantation: [
      "Niveau de soin: facile",
      "Exposition: mi-ombre,ombre",
      "Composition du sol: normal,sableux",
      "Humidité du sol: normal",
      "Température minimale: 12°C",
      "Température maximale: 25°C",
      "Utilisation pour la maison: veranda,intérieur",
    ],
    caracteristiquesVegetales: [
      "Feuillage décoratif: Non",
      "Couleur feuille: vert",
      "Saison d'intérêt: printemps,été,automne,hiver",
      "Feuillage: persistant",
      "Hauteur à maturité: 1 m",
    ],
    botanique: [
      "Origine: Mexique, Guatemala",
      "Rusticité: non rustique",
      "Espèce: elegans",
      "Température minimale: 12°C",
      "Nom botanique: Chamaedora elegans",
      "Famille: Palmiers",
    ],
    price: 25,
    img: [
      "images/miombre22.jpg",
      "images/miombre21.jpg",
      "images/miombre2.jpg",
    ],
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    name: "Zamioculcas",
    category: "ombre",
    id: 3,
    detail:
      "La Zamioculcas est une plante d'intérieur idéale pour décorer votre maison ou votre bureau, très facile à entretenir. Cette plante décorative nécessite une bonne luminosité, mais elle ne doit pas être exposée directement au soleil. L'exposition près d'une fenêtre non orientée sud est idéale.",
    subs: [
      "Décoratif",
      "Feuilles étroites bordées de rouge",
      "Idéal dans de petits espaces",
    ],
    entretienEtPlantation: [
      "Arrosage: sec",
      "Niveau de soin: très facile",
      "Exposition: mi-ombre,ombre",
      "Humidité du sol: normal,sec",
      "Température minimale: 15°C",
      "Température maximale: 30°C",
      "Utilisation pour la maison: veranda,intérieur",
    ],
    caracteristiquesVegetales: [
      "Feuillage décoratif: Non",
      "Couleur feuille: vert",
      "Feuillage: persistant",
      "Hauteur à maturité : 1 m",
    ],
    botanique: [
      "Origine: Régions tropicales",
      "Rusticité: non rustique",
      "Température minimale: 15°C",
      "Nom botanique: Zamioculcas",
      "Famille: Aracées",
    ],
    price: 43,
    img: ["images/ombre31.jpg", "images/ombre32.jpg", "images/ombre33.jpg"],
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    name: "dracaena marginata (3 pieds)",
    category: "ombre",
    id: 1,
    detail:
      "A placer au coin d'un canapé ou près d'une petite table d'appoint, ce Dracaena Marginata s'invite dans la maison et lui confère une touche exotique. C'est une jolie plante verte avec des feuilles joliment striées de rose et de rouge, qui atteint une hauteur de 1,10m environ. Cache-pot vendu séparément.",
    subs: [
      "Décoratif",
      "Feuilles étroites bordées de rouge",
      "Idéal dans de petits espaces",
    ],
    entretienEtPlantation: [
      "Arrosage: normal",
      "Niveau de soin: très facile",
      "Exposition: mi-ombre, ombre",
      "Composition du sol: normal",
      "Humidité du sol: normal",
      "Température minimale: °C",
      "Utilisation pour la maison: intérieur",
    ],
    caracteristiquesVegetales: [
      "Feuillage décoratif: Non Couleur",
      "Feuille: panaché",
      "Saison d'intérêt: printemps,été,automne,hiver",
      "Feuillage: persistant",
      "Largeur à maturité: 0,5 m",
      "Hauteur à maturité: 1,5m",
    ],
    botanique: [
      "Rusticité: non rustique",
      "Espèce: marginata",
      "Température minimale: °C ",
      "Nom botanique: Dracaena marginata",
      "Famille: Agavacées",
    ],
    price: 48,
    img: ["images/ombre21.jpg", "images/ombre22.jpg", "images/ombre23.jpg"],
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    name: "anthurium orange 'matiz'",
    category: "mi-ombre",
    id: 5,
    detail:
      "Les anthuriums sont caractérisés par leurs fleurs à l’aspect cireux. Ils demandent à être placés dans une exposition claire à mi-ombragée mais jamais ensoleillée.Arrosez régulièrement avec de l’eau tiède non calcaire et vaporisez souvent, car ces plantes apprécient que l’air soit assez humide.Fertilisez tous les 15 jours avec un engrais spécial plantes fleuries.Le rempotage des anthuriums se fait tous les 2 à 3 ans dans une terre humifère légère.La couleur peur varier légèrement d'une plante à l'autre Cache-pot vendu séparement.\"",
    subs: [
      "La plante exotique par excellence !",
      "L’anthurium est une très jolie plante ,d’intérieur et de serre.",
    ],
    entretienEtPlantation: [
      "Arrosage: normal",
      "Niveau de soin: très facile",
      "Exposition: mi-ombre",
      "PH du sol: neutre",
      "Composition du sol: sableux,terre de bruyère",
      "Humidité du sol: normal",
      "Température minimale: 15°C",
      "Température maximale: 25°C",
      "Utilisation en jardin: isolé,bac",
      "Utilisation pour la maison: veranda,intérieur",
    ],
    caracteristiquesVegetales: [
      "Feuillage décoratif: Non",
      "Couleur fleur: orange",
      "Couleur feuille: vert",
      "Feuillage: persistant",
      "Période de floraison: novembre à février",
    ],
    botanique: [
      "Rusticité: non rustique",
      "Espèce: X scherzerianum",
      "Température minimale: 15°C",
      "Nom botanique: Anthurium X scherzerianum",
      "Famille: Aracées",
    ],
    price: 33,
    img: [
      "images/miombre31.jpg",
      "images/miombre3.jpg",
      "images/miombre32.jpg",
    ],
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    name: "Dieffenbachia Compacta",
    category: "ombre",
    id: 2,
    detail:
      "Le Dieffenbachia est originaire d’Amérique du Sud.La variété 'Compacta' est d'un vert tendre marginé et tacheté de blanc crème, ce qui lui donne un côté très lumineux.Le Dieffenbachia est une plante particulièrement vigoureuse, qui s’accommode de toutes les situations pour peu qu’elle ne soit pas exposée au soleil direct.",
    subs: [
      "Décoratif",
      "Feuilles étroites bordées de rouge",
      "Idéal dans de petits espaces",
    ],
    entretienEtPlantation: [
      "Niveau de soin: facile",
      "Exposition: mi-ombre,ombre",
      "Composition du sol: normal",
      "Humidité du sol: normal",
      "Température minimale :  °C",
      "Utilisation pour la maison: intérieur",
    ],
    caracteristiquesVegetales: [
      "Feuillage décoratif : Non",
      "Couleur feuille: panaché",
      "Saison d'intérêt: printemps,été,automne,hiver",
      "Feuillage: persistant",
      "Largeur à maturité: 0,5 m",
      "Hauteur à maturité:  1,2 m",
    ],
    botanique: [
      "Origine: Amérique du Sud",
      "Rusticité: non rustique",
      "Température minimale:  °C",
      "Nom botanique: Dieffenbachia ?Compacta?",
      "Famille: Aracées",
    ],
    price: 62,
    img: ["images/ombre1.jpg", "images/ombre11.jpg", "images/ombre12.jpg"],
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  name: "bonsai ficus retusa (8 ans)",
  category: "soleil",
  id: 8,
  price: 105,
  detail:
    "Ficus, Les arbres classés comme d'intérieur sont des arbres qui viennent pour la plupart des climats tropicaux et ne peut donc résister à des températures basses. Nous devons les placer à l'intérieur des maisons, toujours près d'une source de lumière naturelle. Plante tropicale à feuilles persistantes, appréciée pour sa résistance et l'émission de racines aériennes qui lui donnent son caractère.",
  subs: [
    "Feuillage vert toute l'année",
    "Racines aériennes",
    "Facile de culture",
  ],
  entretienEtPlantation: [
    "Arrosage: abondant en été et modéré en hiver",
    "Période de plantation: rempotage tous les 2 ans",
    "Niveau de soin: facile",
    "Exposition: soleil",
    "Composition du sol: normal",
    "Humidité du sol: normal",
    "Température minimale: 15°C",
    "Utilisation pour la maison: veranda,intérieur",
  ],
  caracteristiquesVegetales: [
    " Feuillage décoratif: Non",
    "Feuillage: persistant",
  ],
  botanique: [
    "Origine: Inde, Java, Chine",
    "Température minimale : 15°C",
    "Famille: Moracées",
  ],
  img: ["images/soleil3.jpg", "images/soleil31.jpg", "images/soleil32.jpg"],
  inCart: false,
  count: 0,
  total: 0,
};
